{% set version = "1.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gmm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gmm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gmm/gmm_{{ version }}.tar.gz
  sha256: 194075a3e644ca449a60f4e00c37cce457f4d08ed7229aa62b479f7f8c148f8a

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-sandwich
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-sandwich

test:
  commands:
    - $R -e "library('gmm')"           # [not win]
    - "\"%R%\" -e \"library('gmm')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=gmm
  license: GPL-2.0-or-later
  summary: It is a complete suite to estimate models based on moment conditions. It includes the two step Generalized method of moments (Hansen 1982; <doi:10.2307/1912775>), the iterated GMM and continuous updated estimator (Hansen, Eaton and Yaron 1996; <doi:10.2307/1392442>) and several methods that belong to the Generalized
    Empirical Likelihood family of estimators (Smith 1997; <doi:10.1111/j.0013-0133.1997.174.x>, Kitamura 1997; <doi:10.1214/aos/1069362388>, Newey and Smith 2004; <doi:10.1111/j.1468-0262.2004.00482.x>, and Anatolyev 2005 <doi:10.1111/j.1468-0262.2005.00601.x>).
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: gmm
# Version: 1.6-4
# Date: 2019-12-04
# Title: Generalized Method of Moments and Generalized Empirical Likelihood
# Author: Pierre Chausse <pchausse@uwaterloo.ca>
# Maintainer: Pierre Chausse <pchausse@uwaterloo.ca>
# Description: It is a complete suite to estimate models based on moment conditions. It includes the two step Generalized method of moments (Hansen 1982; <doi:10.2307/1912775>), the iterated GMM and continuous updated estimator (Hansen, Eaton and Yaron 1996; <doi:10.2307/1392442>) and several methods that belong to the Generalized Empirical Likelihood family of estimators (Smith 1997; <doi:10.1111/j.0013-0133.1997.174.x>, Kitamura 1997; <doi:10.1214/aos/1069362388>, Newey and Smith 2004; <doi:10.1111/j.1468-0262.2004.00482.x>, and Anatolyev 2005 <doi:10.1111/j.1468-0262.2005.00601.x>).
# Depends: R (>= 2.10.0), sandwich
# NeedsCompilation: yes
# Suggests: mvtnorm, car, stabledist, MASS, timeDate, timeSeries
# Imports: stats, methods, grDevices, graphics
# License: GPL (>= 2)
# Repository: CRAN
# Repository/R-Forge/Project: gmm
# Repository/R-Forge/Revision: 159
# Repository/R-Forge/DateTimeStamp: 2019-12-04 16:32:33
# Date/Publication: 2019-12-04 18:00:05 UTC
# Packaged: 2019-12-04 16:50:34 UTC; rforge
