travis:
  secure:
    BINSTAR_TOKEN: P2oMw5jiOPwSXju4TBs2LNZwnzIWRIvfmO9sbMlzz9HU8Tudf6adMpp2bcjIz8g0f2isYd4j6HCaDut5mK8kRQUzolE43VQQbk0sdDIbf3NoZlNT4kW+Vje5JshaskYDhs3MI89iphanPvrTXRn3EJSYhvdXyco19eP4+m/B8+pNFzTM4E9BTlPzK3SJZ5Ap7xseTK3jl0hfomdex/24ryb0+z1LaVjouChf3a/+L/DZQRAfuOW7nPd4mPWeO3nlhLrJuTVbPdu8aXffY4qna/WmDZXVoL6o5+Xume9e7Hs76BQ8g4TgrsI1okxrj4PIcux0rr1zhs0O5j+J64PO66ZkoyaRuvUjUqk24XuBBFt3p1G7lq39kR+n2Y9uhTHFTU0iPpm9DnXezJ+HdI7d5wOQNXensKTSX1XfQ2X08nkB2mgTsOMXm8azZ85wG0A6S0PwxhvCdfGZDi1KOOHWpetIMB/LDWdND9lBsAJc72QJsrjY50PenmNn1c7+0LvPWSGQ6CgyIOzo585Sb1wYZjlQNng+pusrPCwVZ5bc+TBfsyuRXEQuR+5vXQ+vC18haF0LXmxLQBeRvubF5BintFTH33q+orfUdDNEWehfz0ptSp2W5/WNEJv+IJl9o7ii17FugLrKmAhCkKILAr2gTlppv1zVnec795TZNxXGLCI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
