appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: tFz9l14alJGUZNCbdTKpZ/Df46xWJAEMsRyP85XMzfyjIvjE2IHgd/ttn6LPi8QT9ToxaslIwAFnRQ+7HOddOoH0bJhf1MJChcgwZWna8nwdIgK4Rbrv2FnPxCCeC/Ij1q32z97MJgAaDU2wMwPWF1CyVyo+pxOCPZdZhjdHsxpN0KPZFWDhogEnlVBYwdzHApLmR2nexxffQhkswNSjrax98kzLv9LCbeLw2W7r10ji8WXyhXRey/Nrv4wbqtZndQt9w7UgXwVj/fT5jncx8vskr77ju49g8k4ea5mT9y0CXRnJ7fOy/z28DOkBYLLr6Tw1rLMjgs8eu+o+Y44q84DIn2sHEDq0YnWZACAwgF+TGiWO0bf6TW37zJS5T4Vm4MwtgTAfw7a5qVZcjWohIO1g1oF+RlykPBQ0rUFrqTurCE2Zhc9wPmKU7xV8wiLZcPliW8fYsjzWrtZaVcdfZRnNqHrAGHdrcERcVSj5AR79MSDRYTSKJx6B9+6B/OozNewOfjk63zz4Z5yEJvIuJA3B/LMZpP7BbJ7qjx1ATuQ/afqLg3nDX4oRqE1kfqul0HYjqqJa4Uw/Jyh8QUyA5BMsP8xhQimYViLJvUfACZPL2hkUk5sJVO3QmW7m7eFoDrMxBMsThRkx8QSSppbGTfGypO1W5arZIB7i1fZKXjY=
