travis:
  secure:
    BINSTAR_TOKEN: NVi1pWYJMADe3VgQMqlbqU1qdoCzX2sUqAEuO2jWei5mTY1XrUBQ41O1KMk7lztvi/g0fMRSPdqT/dPMQvpt2O+y8Uq/nMYs6fgBEXZL5ElgZg0nvr+9syOIW2kv/k774j+fWr60BV1QmWfqfsHkRZwIHFZPqWGh0izinBbt9aYnwGqMROuve7o1KlBWtEJgMaWLIy+oIfpKLJGCqnF1T1xNSfqKKBk0lzV27X4PCG88hzIBF/KJeyLANKqgplpRwsHjjvHTalAIXGH7aWSFqpsb5C7IztFIqg/Snikr1LNOunzi+Zt0u8p+zPcEHi2RaKNpkk0/6HFuEUFS8/bcrzKqrL9EOCjyeNVo7Rj+mazu0VgLNVC8o7TYaVlyqyKOsqnEcMzEhSJXu+ejwXdEGF+cekQUxrIFSSbuTAy8H9G8epyYfJ9E1qAx3wheOeFly1ilt4quYELcCNX/cmuxF53M0qfWoT2cBzSD1wt263JVp60ZpOE/k7iUfiybexGIBy1FrkOnjJMSRtDBkaDoeRKtzm2Lnh4LoorGkVtqj1WdCPLDk5Pj/zN2Dij4xzyBfaPt1eV9ILSg7oiVhepVB2NRAr+e7HytxajK5M4D2DTllrVHzIXTves6mQmo0st8/OF6m1PykP37GULlGpbTVwofergbtLOsBcD67WGgvok=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
